const BLEResponseCommands = {
  WIFI_CONNECTED: "ACK WIFI CONNECTED",
  WIFI_ERROR: "ACK WIFI FAIL",
  ACK_OK: "ACK OK",
  MODE_CREATE: "ACK MODE: CREATE",
  ACK_ERROR: "ACK ERROR",
  DEVICE_CONFIGURED: "ACK CONFIGURED",
};

export default BLEResponseCommands;
